### ISSUE TITLE
Support navigating to the end and beginning of the note

### ISSUE THREAD

**Issue by wenlzhang** [timhor/obsidian-editor-shortcuts#11]
It would be great if this can be supported.

**Comment by timhor** [comment]
You should already be able to do this with native OS shortcuts right?

- Windows: `Ctrl` + `Home`, `Ctrl` + `End`
- macOS: `Cmd` + `↑`, `Cmd` + `↓`

**Comment by wenlzhang** [comment]
> You should already be able to do this with native OS shortcuts right?

Right. I did not notice this before as their effects were replaced by another plugin.
