### ISSUE TITLE
Save All

### ISSUE THREAD

**Issue by LukaWoodson** [timhor/obsidian-editor-shortcuts#14]
Would it be possible to add a save all hotkey for edited files? Or something of the sort? I can't keep up with what I have edited and what I haven't currently.

**Comment by timhor** [comment]
Obsidian should [automatically save](https://help.obsidian.md/How+to/Create+notes) your files already:

> Obsidian automatically saves your note two seconds after you stop typing, or if you close a pane.

If you have a need to manually save multiple open files at the same time, I'd suggest adding a vote to [this feature request](https://forum.obsidian.md/t/save-all-edited-files-or-save-a-backup/284).
