### ISSUE TITLE
[FR] Create a number/bullet when adding lines in a list

### ISSUE THREAD

**Issue by krzemian** [timhor/obsidian-editor-shortcuts#17]
So I've put something together in Keyboard Maestro that allows me to add new lines above/below, which actually adds new numbered entry (as it simulates the [return] keystroke) when in a numbered list. Would you consider setting up the new line shortcuts so that they would do the same (or at least providing an option for that)? Currently they add a blank line, which is not that handy when what you're trying to achieve is to get a new list entry midway through.

**Comment by timhor** [comment]
Yeah, that would be a nice improvement (although maybe best provided as an option instead of default behaviour).

I've tracked it here: https://github.com/timhor/obsidian-editor-shortcuts/projects/1#card-75480884

**Comment by obrovacm** [comment]
Hi there! Any chance we'll get this feature soon? Thanks for your work!

**Comment by timhor** [comment]
Yep! Aiming to resume adding enhancements and features shortly after the new year

**Comment by timhor** [comment]
This is now available in [v1.11.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.11.0) 😀
