### ISSUE TITLE
[FR] more navigation shortcuts for emacs emulation

### ISSUE THREAD

**Issue by bsnodin** [timhor/obsidian-editor-shortcuts#18]
With this plugin I can go a little bit of the way towards emacs-like navigation (e.g. with the plugin I can map a shortcut to go to the start of a line and to go to the end of a line). It would be great if I could use it for other emacs shortcuts, for example by allowing the following to be mapped:
- Go to start/end of current word (skipping to the next word when the cursor is not inside a word; i.e. what ctrl+left arrow and ctrl+right arrow do now)
- Move cursor up/down by one line (i.e. what the up/down arrows do now)
- Go to next/previous character (i.e. what the left/right arrows do now)
- Go to start/end of note
- Go to start/end of paragraph (skipping to the next paragraph when the cursor is not inside a paragraph, analogous to "go to start/end of current word")

**Comment by timhor** [comment]
For this plugin, I'm not intending to add shortcuts for operations that can already be accomplished via native keyboard shortcuts.

I might add paragraph and word navigation to the [Sentence Navigator](https://github.com/timhor/obsidian-sentence-navigator) plugin in the future.

If you're looking for a more comprehensive Emacs experience though, I'd suggest weighing in on [this feature request](https://forum.obsidian.md/t/emacs-bindings-in-the-editor/734). Apparently CodeMirror supplies an Emacs bindings package so someone may be able to utilise it to bring that functionality to Obsidian.

**Comment by bsnodin** [comment]
Ah right, thanks. Thanks too for the links.
