### ISSUE TITLE
Remove Delete line?

### ISSUE THREAD

**Issue by WhiteNoiseDev** [timhor/obsidian-editor-shortcuts#19]
Is "delete line" the same as "delete paragraph" built in obsidian?
Side-Note: the new editor has ctrl-shift-k already bind to delete line.

**Comment by timhor** [comment]
> Is "delete line" the same as "delete paragraph" built in obsidian?

It's basically the same, but I noticed a slight discrepancy in the behaviour of _Delete paragraph_ between Mac and Windows so I'll keep _Delete line_ here for now.

- On Mac, using _Delete line_ on the last line of a note will delete the entire line AND move the cursor to the previous line (consistent with VS Code's behaviour) whereas _Delete paragraph_ will only clear the contents of the line.
- On Windows, both of them do the same thing.

> Side-Note: the new editor has ctrl-shift-k already bind to delete line.

I see the default binding as `Ctrl`+`D` on v0.13.19.
