### ISSUE TITLE
Merge `Expand selection to quotes` and `Expand selection to Brackets` into one command

### ISSUE THREAD

**Issue by chrisgrieser** [timhor/obsidian-editor-shortcuts#21]
many code editor basically merge those two commands in an "smart expand" command that looks ahead and behind whichever the current scope is. I am a bit used to having both in one command, so it's kind of weird for me to use them as two commands here. And I assume it shouldn't be hard to implement, since the bracket command already considers multiple different types of brackets?

**Comment by timhor** [comment]
Yeah you're right, I could combine the bracket and quote regex to achieve that. I'd also need to tweak the behaviour slightly though as it currently doesn't widen the search if the command is run again. Tracked the request here: https://github.com/timhor/obsidian-editor-shortcuts/projects/1#card-76569600.

To give some context as to why I initially made them separate: I'm used to using an extension ([Quick and Simple Text Selection](https://marketplace.visualstudio.com/items?itemName=dbankier.vscode-quick-select)) which lets you specify exactly what to expand the selection to, so the built-in smart select functionality didn't occur to me before.
