### ISSUE TITLE
[Feature Request] New Command: Select Table

### ISSUE THREAD

**Issue by FelipeRearden** [timhor/obsidian-editor-shortcuts#24]
Hello @timhor !!!!!!

Before talking about my FR, I wanna say thank you for creating this amazing plugin. I use it a lot and everyday :)

## My FR

My FR is simple to explain: would be amazing if we have a new command to select a markdown table.

It’s the same meaning of `Select Word` Applied to markdown tables: if the caret cursor is inside a table,it will select the whole table when the new command is pressed 

## Why Are you asking for this FR?

Let me explain: there is a new plugin in beta called [Markdown Table Editor](https://github.com/ganesshkumar/obsidian-table-editor#12-edit-and-format-an-existing-markdown-table) that lets you edit markdown tables inside Obsidian !
- The starting point of the plugin is to have the table that will be edited **selected** before hitting the command.

That’s why I’m asking for this feature :) 

---

Thanks for reading this! 

Have a great day!!!!!!

**Comment by timhor** [comment]
Hey @FelipeRearden, thanks for the feedback, it means a lot!

Looking at your feature request, I wonder whether it makes more sense for this to be implemented by the Table Editor plugin instead. If it's always necessary to have the table selected before making edits, a nice improvement would be to automatically select the entire table when activating the plugin (or to support edits with the cursor anywhere inside a markdown table).

**Comment by FelipeRearden** [comment]
Hello @timhor !!!!

> Hey @FelipeRearden, thanks for the feedback, it means a lot!

😃 

> Looking at your feature request, I wonder whether it makes more sense for this to be implemented by the Table Editor plugin instead. 

I 100% understood your comment :) 

I thought about this before writing this FR for you ... 

In my user limited mind, would less difficult for Obsidian Editor Shortcuts to add this additional feature (I'm assuming that the engine to select a table should be similar to the engine of `Select Word` and `Select Line` ) than for Markdown Editor Table to create a new engine for this feature.

> If it's always necessary to have the table selected before making edits, a nice improvement would be to automatically select the entire table when activating the plugin (or to support edits with the cursor anywhere inside a markdown table).

That exactly what I thought :) 

For this, my idea is to use QuickAdd Macro to stack these two commands into a single hotkey to get the same behavior. 

---

Feel free to close this issue if you think it's is something that you feel that is not a good feature to this amazing plugin. 

At least I'm happy to have the opportunity to connect with you for the first time and to share with you a new workflow :)

Thanks for reading this!!!!

Have a great day!!!!

**Comment by timhor** [comment]
> would less difficult for Obsidian Editor Shortcuts to add this additional feature

Finding the start/end of a word is relatively simple since we only need to search for word boundaries on a single line, whereas finding the start/end of a table would require some additional logic to locate the first and last rows. That logic doesn't exist in this plugin at the moment, so the effort would be roughly similar IMO.

> Feel free to close this issue if you think it's is something that you feel that is not a good feature to this amazing plugin.

I'm always open to suggestions 😀 your request has been noted here: https://github.com/timhor/obsidian-editor-shortcuts/projects/1#card-78414951. But as with the other ideas on that board, keep in mind it will be a while before I'll get around to it since I have limited spare time outside of work (and that list is getting long!) – hence my suggestion to raise it with the other plugin's author first.

> At least I'm happy to have the opportunity to connect with you for the first time and to share with you a new workflow :)

Likewise, I appreciate it!

**Comment by FelipeRearden** [comment]
Thanks for considering this in the future and for your technical explanation  !!!!!!

I will follow your recommendation and create a new FR at MTE. I update you about it in the future. 

Thanks again for you time and I wish you the best :)

Let's keep talking!

**Comment by timhor** [comment]
Closing as it has been implemented in https://github.com/ganesshkumar/obsidian-table-editor/issues/8

**Comment by FelipeRearden** [comment]
> Closing as it has been implemented in https://github.com/ganesshkumar/obsidian-table-editor/issues/8

100% agree @timhor . Sorry for forget to close this FR in the past.
