### ISSUE TITLE
Duplicate line in sidebar bug

### ISSUE THREAD

**Issue by NomarCub** [timhor/obsidian-editor-shortcuts#26]
Executing the duplicate line command in a sidebar document now does them in the main edited document instead.

**Comment by timhor** [comment]
I was able to reproduce; however, it isn't specific to this plugin. The same thing happens if you try to run built-in editor commands (such as toggle bold, toggle heading, swap line up). Could you raise this as a bug with Obsidian [here](https://forum.obsidian.md/c/bug-reports/7)?

**Comment by NomarCub** [comment]
Thanks! I found it tracked [here](https://forum.obsidian.md/t/hotkeys-commands-should-apply-to-sidebar-notes-when-they-are-focused/2740). There's some talk in the thread about it being fixable via plugins.
