### ISSUE TITLE
[Feature Request] `Select Word` command: Support for non-ASCII characters (e.g. á ã é í ó )

### ISSUE THREAD

**Issue by FelipeRearden** [timhor/obsidian-editor-shortcuts#28]
Hello again @timhor !!!!!!

My FR is to add support for non-ASCII characters to the command `Select Word` :)

When you select a word in a language like Portuguese or Finnish, we have this as result:

![8F8539F5-736B-42FE-9FE9-0DD753085AD4](https://user-images.githubusercontent.com/85180696/161397044-da86b938-c761-4145-b1b2-80991f29dfe4.jpeg)
![49BEB65A-65EB-4CF6-A7A3-A6568AB10A14](https://user-images.githubusercontent.com/85180696/161397046-6b29262a-cd33-4f17-9282-a6027bc788bc.jpeg)

As you can see form the images, it’s only selecting the characters until the non-ASCII characters.

This is a list of non-ASCII characters for the Portuguese and Finnish language:

`áàâãéèêíïóôõöúçÁÀÂÃÉÈÍÏÓÔÕÖÚÇ`

### My Background 

Since I was born in 🇧🇷, Portuguese is my  mother language. These type of characters are the used in every portuguese word as you can see above:

| *English* | *Portuguese* |
|:----------|:-------------|
| Coffee    | Café         |
| Sugar     | Açúcar       |
| John      | João         |

The same behavior applied to 🇫🇮 and many countries :) 

---

I hope you could add support for these characters 🙏 🙏 🙏 .

Thank you very much for reading this !!!

Have a great day 🌞

**Comment by timhor** [comment]
Thanks for the detailed explanation!

I can definitely add support for these characters, this should be an easy fix 😀 I'll update you here once it's done.

**Comment by FelipeRearden** [comment]
> Thanks for the detailed explanation!

Thank you very much for the feedback!!!!!

> I can definitely add support for these characters, this should be an easy fix 😀 I'll update you here once it's done.

Thank you very much 🎉 🎉 🎉 

I'm glad to know that is an easy fix 🤓

You have no idea how happy I am now !!!!!!!!

Thank you very much and have a great day 🌞 !!!!!

**Comment by timhor** [comment]
Released in https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.8.0 🥳

**Comment by FelipeRearden** [comment]
Thank you very much @timhor !!!!!!!

Working perfect on version `1.8.0` Obsidian `0.14.6`

Thanks again for this fix, means a lot to em :)


Have a great day 🌞
