### ISSUE TITLE
[feature request] join lines in selection with ctrl+j

### ISSUE THREAD

**Issue by zeigo** [timhor/obsidian-editor-shortcuts#30]
For VSCode, you can select multiple lines and join them into one line with a shortcut. Is it possible for this plugin?

**Comment by timhor** [comment]
Yes that can be done. Tracked here: https://github.com/timhor/obsidian-editor-shortcuts/projects/1#card-80593623.

To clarify, you're talking about selecting multiple lines in one go before joining, right? As opposed to adding a new cursor to each line.

**Comment by zeigo** [comment]
yes
