### ISSUE TITLE
Feature Request Delete to Start of Line

### ISSUE THREAD

**Issue by brimwats** [timhor/obsidian-editor-shortcuts#33]
Opposite of the Delete to End of Line command. I use the sentence Navigator plugin for this but it would be great to remove this and just keep code editor

**Comment by timhor** [comment]
Noted and tracked here: https://github.com/timhor/obsidian-editor-shortcuts/projects/1#card-81078107

**Comment by FelipeRearden** [comment]
Hello @timhor and @brimwats 

+1 for this FR 👍

Just to let you know that there is a new plugin called [Doubleshift](https://github.com/Qwyntex/doubleshift) that is a perfect companion for the commands `Delete to the End` and `Delete to the Start` 

This plugin lets you define a command from Command Palette when you hit some keyboard keys **twice**:
- SHIFT SHIFT
- TAB TAB
- HOME HOME
- END END 
- BACKSPACE BACKSPACE
- DELETE DELETE
- and so ....


Might be a good idea to use :

`Delete to the End` = DELETE DELETE
`Delete to the Start` = BACKSPACE BACKSPACE

Have a great day 🌞

**Comment by timhor** [comment]
This is now available in [v1.9.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.9.0)
