### ISSUE TITLE
Some hotkeys don't work on mac

### ISSUE THREAD

**Issue by zcysxy** [timhor/obsidian-editor-shortcuts#34]
I'm on macOS, Obsidian v0.14.7. Some default hotkeys don't work, like `cmd + D` and `cmd + enter`. However I can execute these commands from the command palette. Also, if I bind them to other hotkeys, like `cmd + Q` and `ctrl + shift + Enter`, then they will work.

Also, I use Advanced Cursors before, which also has a feature to select word/ next occurrence. I used to bind this command to `cmd + D` as well, and it worked fine.

**Comment by timhor** [comment]
Is it possible those hotkeys are conflicting with the default bindings? `Cmd`+`D` and `Cmd`+`Enter` are automatically bound to certain built-in commands (`Delete paragraph` and `Toggle checkbox status` respectively) by default.

**Comment by zcysxy** [comment]
@timhor Thanks for the reply! I have already removed these default bindings. Therefore I mentioned that for `cmd + D`, Advanced Cursors works for me.

**Comment by timhor** [comment]
In that case, I'm not too sure... I just tried creating a new vault, installing the plugin and disabling the default hotkeys, and it works as expected.

Does it work for you on the stable version, 0.14.6?

**Comment by zcysxy** [comment]
I'm so sorry that I didn't check more carefully. Yeah it also works for me in the help vault. It's another plugin called Completr that is interfering with the hotkeys. Some other hotkeys like `toggle bullet list` also don't work if Completr is turned on
