### ISSUE TITLE
Go to end of line / Go to start of line not working

### ISSUE THREAD

**Issue by reinvented** [timhor/obsidian-editor-shortcuts#36]
I've assigned Command + Right Arrow to "Go to end of line" and Command + Left Arrow to "Go to start of line" on my Mac:

![Screen Shot 2022-05-16 at 8 10 36 AM](https://user-images.githubusercontent.com/328524/168580753-102fdeaa-d62c-4b98-86f7-7861bb8e52ee.png)

This is having no effect, however. Plugin is installed and enabled, and working otherwise.

**Comment by timhor** [comment]
They both have a red background which means they're conflicting with other hotkey assignments. What does it say when you hover over those buttons?
