### ISSUE TITLE
Add `vscode` to the description for easy searching

### ISSUE THREAD

**Issue by gsteve3** [timhor/obsidian-editor-shortcuts#4]
Installing this plugin for the several dozenth time on a new vault , had trouble remembering the name though.

## What I Did

From within Obsidian, when **_Browsing Community Plugins_**, I tried searching for:

### 1. `vscode`

- So used to calling it `vscode` I never even thought to search just `code` or `Visual Studio Code`.
- Only result is another plugin I quite like, https://github.com/NomarCub/obsidian-open-vscode

### 2. `alt up` (and variants/variations?)

- Hoping to find it by the keyboard shortcut I wanted to use to copy a line up/down.

### 2. `edit`

- Hoping to find "code editor" or something like that.
- Lots of results, but I found you! ♥

## What I _think_ could be Better

- Recommend adding `vscode` somewhere in the description that shows up in the screenshot.
- I will/can/fork/whatever if you like, just busy at the moment and I knew I'd forget this.
- So used to filing issues in daily work these seemed natural.
- Sorry if annoying, and thank you for the extension 🙏

---

![image](https://user-images.githubusercontent.com/7085720/142068624-896f693b-baec-44da-9f47-9c3de2522a99.png)

**Comment by timhor** [comment]
Sure thing, thanks for the suggestion. Good to make it more discoverable.
