### ISSUE TITLE
[Feature Request] move cursor up and down

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [timhor/obsidian-editor-shortcuts#40]
At first , thanks very much for this plugin, it's a good way, and the only way AFAIK to implement emacs keybindings in obsidian on windows and linux OS.
I notice that there are move cursor right / left commands and go to previous line /next line commands, but emacs need move cursor up and down commands, because go to previous line is not useful on the lines which are wraped, I need move up as i see,not the previous line as the editor deal with.

**Comment by timhor** [comment]
I don't have a clear idea of what cursor movements look like in code when dealing with wrapped lines, but I can look into this at some point.

Tracked here: https://github.com/timhor/obsidian-editor-shortcuts/projects/1#card-85220847

**Comment by timhor** [comment]
This is now available in [v1.13.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.13.0)
