### ISSUE TITLE
Detecting if cursor is within a codeblock

### ISSUE THREAD

**Issue by thelegend09** [timhor/obsidian-editor-shortcuts#41]
I appreciate that you specify "Ctrl + Enter for 'Insert line below' may conflict with the default shortcut for Toggle checklist status; changing/removing one of the bindings is recommended."

In Obsidian, I'd love to be able to use Ctrl + Enter for "Insert line below" when I'm in a code block, but keep it for "Toggle checklist status" when I'm anywhere else.

Not sure if/how that is possible, though.

**Comment by timhor** [comment]
Hmm unfortunately I can't really see a way to make that happen since the 'Toggle checklist status' functionality exists outside this plugin, so one hotkey would inevitably override the other.

**Comment by thelegend09** [comment]
I get it. Too bad.

Thanks for all the other amazing functionalities though!
