### ISSUE TITLE
[Feature Request] Custom selection transform

### ISSUE THREAD

**Issue by vkhobor** [timhor/obsidian-editor-shortcuts#42]
Hi! 

I was looking for a way to transform selected text to other formats. My use case was that I wrote a list comma separated and not markdown formatted, and I wanted to transform it via a command.

From:
```
apple, banana
```
To:
```
- apple
- banana
```
I've seen this plugin supports `Transform selection to uppercase` which is similar, only the logic is different.

I was wondering if something like `Transform selection to uppercase` with custom js code could be supported or if you know any plugins that have this functionality.

Thank you for the help.

**Comment by timhor** [comment]
You could use `Select all occurrences of selection` to select the comma delimiters and then press `Enter` and `-`? That should get you most of the way for this use case.

If it's a common action you need to perform, you can also create a macro to chain those operations in the [QuickAdd plugin](https://github.com/chhoumann/quickadd).
