### ISSUE TITLE
[Feature Request] Strip markdown from selected text

### ISSUE THREAD

**Issue by MagePrometheus** [timhor/obsidian-editor-shortcuts#43]
Just an idea. Probably complex to handle nested quote characters right unless there is a js library already available.

**Comment by timhor** [comment]
Thanks for the suggestion. I'd suggest requesting this in a plugin like [Smarter Markdown Hotkeys](https://github.com/chrisgrieser/obsidian-smarter-md-hotkeys) instead as it's more of a markdown-related behaviour than a standard code editor functionality.

**Comment by MagePrometheus** [comment]
Thanks for the link. I've noticed this plugin but never loaded it as I know markdown pretty well after keeping my notes in QOwnNotes for many years. It's amazing how quickly I find myself unable to live without Obsidian!
