### ISSUE TITLE
[Feature Request] Vertical select

### ISSUE THREAD

**Issue by robinsonkwame** [timhor/obsidian-editor-shortcuts#44]
E.g. alt/option - command + up or down arrow to vertically insert cursors across multiple lines. Apologies if I overlooked something and this is already possible!

**Comment by timhor** [comment]
Can do 🙂 follow along here: https://github.com/timhor/obsidian-editor-shortcuts/projects/1#card-86401295

**Comment by tonyxiao** [comment]
Was just looking for this. Subscribed. Yay!

**Comment by timhor** [comment]
This is now available in [v1.11.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.11.0) 😀
