### ISSUE TITLE
[Feature request] Next Prev word as in vscode or visual studio

### ISSUE THREAD

**Issue by drventure** [timhor/obsidian-editor-shortcuts#45]
Great plugin BTW!

Oddly, Obsidian doesn't implement Previous word/next word and it seems like this plugin would be an ideal candidate to implement that.

You've already got all the basic nav actions supported, just missing the next prev word....

**Comment by timhor** [comment]
Thanks, I'm actually planning to address that in my other plugin which already has a similar feature request! Check out https://github.com/timhor/obsidian-sentence-navigator/issues/3

**Comment by drventure** [comment]
Oh. Fantastic. I didn't realize you had another one out there. I'll check it out! Thanks!

**Comment by timhor** [comment]
Found an easy way to add this feature, so it's now included in [v1.13.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.13.0)
