### ISSUE TITLE
[Feature Request] Move whole line/selection up/down using Alt + Cursor Up/Down

### ISSUE THREAD

**Issue by PrinceCharles23** [timhor/obsidian-editor-shortcuts#46]
I find this feature (from Visual Studio) pretty helpful to reorder e.g. lists.

e.g.;
line one
line two
line three
line four

So if i select line two and line three and press Alt + Cursor Down i get:

line one
line four
line two
line three

**Comment by timhor** [comment]
Obsidian already has built in hotkeys for "Move line up" and "Move line down"

**Comment by PrinceCharles23** [comment]
you are absolutely right! i obviously did not know that, sorry! thanks! and thanks for the plugin - there are still a few hotkeys missing in Obsidian ;-)

**Comment by timhor** [comment]
No problem! 😀
