### ISSUE TITLE
[Feature Requests] toggle line numbers inside editor

### ISSUE THREAD

**Issue by wuzhen97** [timhor/obsidian-editor-shortcuts#50]
Hello，I think it‘s may useful to add a shortcut that toggle line numbers inside editor like  [the plugin](https://github.com/KrazyManJ/obsidian-keyshots)

**Comment by timhor** [comment]
This is now available in [v1.12.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.12.0)
