### ISSUE TITLE
[Feature Request] New command: Toggle Case

### ISSUE THREAD

**Issue by pdelre** [timhor/obsidian-editor-shortcuts#51]
In addition to the existing "Transform selection to x case", it'd be nice to support a "Toggle Case" which can rotate through the three states (upper, lower, title). This functionality is covered in another plugin, https://github.com/MatthewAlner/obsidian-toggle-case, but feels like a better fit to add the feature here than install an additional plugin.

Thank you for the plugin!

**Comment by timhor** [comment]
This is now available in [v1.12.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.12.0), thanks to #47 by @MatthewAlner

**Comment by pdelre** [comment]
TYVM @MatthewAlner & @timhor!
