### ISSUE TITLE
inserting a line after frontmatter fence

### ISSUE THREAD

**Issue by huyz** [timhor/obsidian-editor-shortcuts#52]
If the cursor is on a boundary of frontmatter and I insert a line, I get a line with a `-`.  But this isn't a list item--it's just a fence.

```markdown
--- %%cursor could be here%%
tags:
updated: '2023-01-09 11:06-08:00'
created: '2023-01-09 11:06-08:00'
--- %%or cursor could be here%%
- %%inserting a line incorrectly adds a `-`%%
```

**Comment by timhor** [comment]
Nice catch! Fixed in [v1.12.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.12.0)
