### ISSUE TITLE
Inserting a line doesn't recognize checbox lists

### ISSUE THREAD

**Issue by tobiasvl** [timhor/obsidian-editor-shortcuts#53]
In vanilla Obsidian, if the cursor is in a checkbox list and you insert a new line, it will create a new empty checkbox (`- [ ] `).

However, this plugin will instead insert a regular list item bullet point (`- `)

Note that the inserted checkbox should always be empty, regardless of the status of the checkbox of the line the cursor is on. It should also recognize "[alternate checkboxes](https://forum.obsidian.md/t/alternative-checkboxes-icon-bullets-copy-and-paste/35962)", which are supported by most themes.

**Comment by tobiasvl** [comment]
Perhaps related to #52

**Comment by timhor** [comment]
This should now work as expected in [v1.12.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.12.0)
