### ISSUE TITLE
Can't update to 1.13.1

### ISSUE THREAD

**Issue by AndyLiu9** [timhor/obsidian-editor-shortcuts#59]
Thanks for your plugin. But I can't update to version 1.13.1, could you please help with this issue?

**Comment by timhor** [comment]
v1.13.1 is still in draft; I should have it wrapped up over the weekend.

You'll find it listed on the [releases page](https://github.com/timhor/obsidian-editor-shortcuts/releases) once it's ready 🙂

**Comment by timhor** [comment]
Should be fixed now! (Pushed up the git tag for the release before it was ready to be published)
