### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by fredcallaway** [timhor/obsidian-editor-shortcuts#60]
I'm trying to install the plugin in the standard way (browse community plugins). When I click install, it gives me an error message: "Failed to install plugin"

The console spits out a not-very-informative error as well
```
app.js:1 Error: Request failed, status 404
    at new t (app.js:1:717762)
    at Jw (app.js:1:717954)
    at app.js:1:718631
    at app.js:1:235836
    at Object.next (app.js:1:235941)
    at a (app.js:1:234680)
```

I'm running Obsidian Version 1.1.16 on macOS Monterey 12.3.1.

**Comment by timhor** [comment]
Thanks for letting me know, should be fixed now!
