### ISSUE TITLE
"Go to line number" goes to the last line if entering a number larger than the last line

### ISSUE THREAD

**Issue by vanbang9710** [timhor/obsidian-editor-shortcuts#62]
For example, if a note has 200 lines. Entering any number >200 will jump to line 200

**Comment by timhor** [comment]
Currently the modal already informs you of the line number range in the current file, and it intentionally does nothing if the number entered is outside of this range.

![image](https://user-images.githubusercontent.com/14193387/234841893-34abec38-b154-406e-ac32-342b02730da0.png)

**Comment by vanbang9710** [comment]
When using mobile or small keyboard, I don't have the shortcut "Ctrl+End" to go to the last line. So I would use "Go to line", spam "99999" to do this

**Comment by timhor** [comment]
Could this be achieved via the dedicated 'Go to last line' action instead?

**Comment by vanbang9710** [comment]
It works! I didn't find it because I tried searching for command "begin" or "start"
