### ISSUE TITLE
Select line unusual (moves cursor to end of line)

### ISSUE THREAD

**Issue by reagle** [timhor/obsidian-editor-shortcuts#64]
Thanks for the plugin! 

I'm using `Select line (repeat to keep expanding selection)` and it has odd behavior -- at least to my expectations in Sublime Text and Visual Studio Code. If I select this command three times on the following code and then "add cursor to line ends" (in VSC) or "Split selection into lines" (in ST4), I have three cursors, at the end of each line.

    This is a test;
    of the emergency broadcasting system.
    If this had been a real test...

<img width="419" alt="SCR-20230505-mjrl" src="https://user-images.githubusercontent.com/596814/236533114-09b7d8a3-46ad-418b-8a34-c1cd939ca537.png">

Your plugins adds a fourth cursor on the following blank line, which confuses multi-cursor edits. (The screen capture only caught one cursor, they blink out of time with each other, but there are four.)

<img width="385" alt="SCR-20230505-mjvf" src="https://user-images.githubusercontent.com/596814/236533115-bd841129-fcc7-42eb-b2e0-39e585ffb4d7.png">

**Comment by timhor** [comment]
Ah I see what's going on – Sublime and VS Code don't add a cursor to the final line if it's blank.

Should be a easy fix for this edge case.

**Comment by reagle** [comment]
I don’t think it’s just for a final blank line, though that’s the context in which I first encountered this. If I select three lines among five and split, I should have three cursors, whether the following line was empty or not.

**Comment by timhor** [comment]
Oh yep you're right – it's happening because select line always selects until the beginning of the next line. I'll fix up the behaviour for adding cursors / splitting selections.

**Comment by timhor** [comment]
This has been fixed in [v1.14.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.14.0)

**Comment by reagle** [comment]
Confirm fixed. Thank you!
