### ISSUE TITLE
[FR] Undo and Redo

### ISSUE THREAD

**Issue by Remodor** [timhor/obsidian-editor-shortcuts#66]
Hello again,

another feature request would be shortcuts for undo and redo. `ctrl + z` and `ctrl + shift + z`.

Thank you again!

**Comment by timhor** [comment]
For more context (same with #65), can you share why you're looking to remap these standard OS-level shortcuts in Obsidian? 🙏

**Comment by timhor** [comment]
Can you share some context as to why you're looking to remap these standard OS-level shortcuts in Obsidian (same with https://github.com/timhor/obsidian-editor-shortcuts/issues/65)? It should be easy enough to do but I'm curious to understand a bit more 🙏

**Comment by Remodor** [comment]
I map all my shortcuts to `alt`, similar as you would use vim. As soon as you get used to it, it feels very quick very intuitive. `alt + ESDF` navigation, `alt + u` undo, `alt + U` redo, `alt + d` delete line, `alt + c` delete word in front of cursor, `alt + capslock` (which I remapped to backspace by default) delete word in back of cursor. Etc..

There are many things I actually remap to `alt`, (basically all) because it is so easily reachable with the thumb :)

**Comment by timhor** [comment]
Undo and redo can now be remapped in [v1.14.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.14.0)
