### ISSUE TITLE
Target line for "Duplicate line"

### ISSUE THREAD

**Issue by hidehide55** [timhor/obsidian-editor-shortcuts#68]
Thanks for the great plugin.

If the cursor is at the beginning of a line after selecting multiple lines, I would like the cursor line to be excluded from the duplicate.
I don't want line "333" in the gif video below to be duplicated.
![obsidian](https://github.com/timhor/obsidian-editor-shortcuts/assets/6263325/ded9abee-5725-4cd2-89aa-523228ad9bc3)

The gif video below shows the behavior in vscode.
![vscode](https://github.com/timhor/obsidian-editor-shortcuts/assets/6263325/70e534bd-eb94-4ad3-aa69-e971e4402e18)

Thanks.

**Comment by timhor** [comment]
Noted! I'll tackle this along with https://github.com/timhor/obsidian-editor-shortcuts/issues/64 as they share the same root cause

**Comment by hidehide55** [comment]
Thank you for releasing 1.14.0.
I have confirmed that this problem has been fixed in 1.14.0.

Thanks.
