### ISSUE TITLE
FR: Join Lines removing bullets points

### ISSUE THREAD

**Issue by chrisgrieser** [timhor/obsidian-editor-shortcuts#7]
say I want to merge two lines:

```md
- one point
- second point
```
here, the result would be: 

```md
- one point- second point
```

A much more elegant result, however, would be to remove the preceding `-`:

```md
- one point second point
```

**Comment by timhor** [comment]
I'm a bit hesitant about this one as it starts to diverge from the code editor behaviour I'm trying to emulate. If it becomes a feature, might be better to have it as a configurable option so users aren't surprised with a missing dash.

**Comment by timhor** [comment]
Tracked here: https://github.com/timhor/obsidian-editor-shortcuts/projects/1#card-75480854
