### ISSUE TITLE
"Smarter Insert New Line" doesn't work anymore

### ISSUE THREAD

**Issue by Stakker** [timhor/obsidian-editor-shortcuts#75]
Seems to behave like regular enter. Have tried different key combinations, so it's not that.

**Comment by timhor** [comment]
Does it work if you invoke the action using the command palette (`Cmd`+`P`)? If so, there may be a conflicting hotkey.

Otherwise can you provide some more details to help diagnose? Obsidian / plugin version, steps to reproduce?

**Comment by Stakker** [comment]
Ahh, yeah seems that this works again. Some update fixed it, I guess. Sorry for not remembering to close this!
